name: Continuous Integration

on:
  push:
    branches:
      - 'release*'
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Validate ReportTemplate folder exists and is not empty
        run: |
          if [ ! -d "ReportTemplate" ]; then
            echo "❌ ReportTemplate folder does not exist in the root directory."
            exit 1
          fi
          if [ -z "$(ls -A ReportTemplate)" ]; then
            echo "❌ ReportTemplate folder is empty."
            exit 1
          fi
          echo "✅ ReportTemplate folder exists and is not empty."
          
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
